#Author: Alexey Usov (dax@xdax.ru, https://t.me/doubleaxe, https://github.com/doubleaxe)
#Please don't remove this comment if you use unmodified file
root: true
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: es2022
    sourceType: module
extends:
    - eslint:recommended
    - "plugin:@typescript-eslint/recommended"
    - ./.eslintrc.aousov.base.js.yml
    - ./.eslintrc.aousov.base.ts.yml
    - ./.eslintrc.aousov.codestyle.yml
    - ./.eslintrc.aousov.codestyle.ts.yml
plugins:
    - "@typescript-eslint"
